## when the restart hass boolean is set to true, restart hass
- alias: Restart HASS 
  hide_entity: False
  trigger:
    platform: state
    entity_id: input_boolean.restart_hass
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.restart
