
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 38.2733
  longitude: -77.1739
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 68
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customized.yaml
media_layer: !include devices/media_players.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: jzheadley.duckdns.org:8123
  # SSL for remote access
  # ssl_certificate: /etc/letsencrypt/live/jzheadley.duckdns.org/fullchain.pem
  # ssl_key: /etc/letsencrypt/live/jzheadley.duckdns.org/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
    units: us
    update_interval: '00:30:00'

  - platform: speedtest
    monitored_conditions:
      - download
      - upload
      - ping
    minute:
      - 0
      - 15
      - 30
      - 45

  - platform: systemmonitor
    resources: 
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: since_last_boot

# Text to speech
tts:
  platform: google

automation: !include automation.yaml

ifttt:
  key: !secret ifttt_key

input_boolean:
  restart_hass:
    initial: off

group: !include groups.yaml
